### ISSUE TITLE
Add part 3 to Piggy Bank tutorial which uses cargo-concordium and concordium-client

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-rust-smart-contracts#114]
**Task description**

The piggy bank tutorial currently covers implementing and testing a smart contract. But using and understanding cargo-concordium and concordium-client is also a crucial part of developing smart contracts.
The goal of this task is to add a third part to the Piggy Bank tutorial which uses cargo-concordium and concordium-client.

**Sub-tasks**
- [ ] Get everything set up (node, concordium-client (with keys from mobile wallet), cargo-concordium, the part 2 contract)
- [ ] Build the contract with cargo concordium
- [ ] Deploy the contract (explain how to connect to your node with grpc)
- [ ] Initialize the contract
- [ ] Update the contract
- [ ] Invoke the contract (with `concordium-client contract invoke`)
