### ISSUE TITLE
concordium-std improvements

### ISSUE THREAD

**Issue by smh1001** [Concordium/concordium-rust-smart-contracts#126]
concordium-std has been updated to V1 smart contracts but there are a number of opportunities for improvement both in performance (reducing code size, reducing complexity) as well as adding functionality.  Programmer/user ergonomics are key for anything here, so a large part of any improvement must be design considerations.

- Add ability to return error messages from init/receive entrypoints. This is not currently possible with concordium-std, but the chain allows it.
- Integrate these return values into the schemas and allow them to be pretty printed by the client.

The following issues/bugs should be addressed
- [x] https://github.com/Concordium/concordium-rust-smart-contracts/issues/123
- [x] https://github.com/Concordium/concordium-rust-smart-contracts/issues/118
- [x] https://github.com/Concordium/concordium-rust-smart-contracts/issues/93
- [x] https://github.com/Concordium/concordium-rust-smart-contracts/issues/78
- [x] https://github.com/Concordium/concordium-rust-smart-contracts/issues/64
- [ ] https://github.com/Concordium/concordium-rust-smart-contracts/issues/97
- [x] https://github.com/Concordium/concordium-contracts-common/issues/43
- [x] https://github.com/Concordium/concordium-rust-smart-contracts/issues/76
