### ISSUE TITLE
upgradable wCCD token

### ISSUE THREAD

**Issue by smh1001** [Concordium/concordium-rust-smart-contracts#129]
**Task description**

Most smart contract protocols have some common features such as pausing and upgrading. This task will add the following features to the wCCD token:

**Sub-tasks**

- [ ] Adding an admin address that is authorized to do maintenance tasks in the smart contract. https://github.com/Concordium/concordium-rust-smart-contracts/pull/128

- [ ] Adding the capability to pause contract by the admin address. https://github.com/Concordium/concordium-rust-smart-contracts/pull/128

- [ ] Adding pattern to upgrade the implementation contract. https://github.com/Concordium/concordium-rust-smart-contracts/pull/128

**Comment by DOBEN** [comment]
Closed until we have a final decision on if native upgradable smart contracts are supported by the blockchain.
