### ISSUE TITLE
wCCD documentation

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-rust-smart-contracts#131]
**Task description**

Documenting the w_ccd contract and adding a tutorial if needed.

**Sub-tasks**
- [ ] Descriptions of the general functionalities of a wrapped token contract

- [ ] Explicit descriptions of the new features added to the wCCD smart contract

- [ ] Descriptions on how front-ends can listen for events

- [ ] An example interaction with a state-mutative function

- [ ] An example interaction with a non-state-mutative function

- [ ] Off-chain app example with a “wrap”, “unwrap”, “set_operator”, and “transfer” button

- [ ] Integration example with the Rust SDK
