### ISSUE TITLE
Introduce schemas for errors

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-rust-smart-contracts#155]
**Task description**

Currently, when a smart contract produces an error, the user is shown an error code. The user then has to figure out the mapping between the error code and the error type.

This can be improved by allowing the user to specify a schema for the error type, similar to what is possible for the `parameter` and `return_value`.

Example:
```
#[derive(SchemaType)]
enum MyError {
    NotOwner,
    OnlyAccountsAllowed,
}

#[receive(... error= "MyError")]
fn receive() -> Result<(), MyError> {...}
```

The tools will need to be updated to handle the new, optional, error schema. This includes cargo-concordium, concordium-client, and our NodeJS SDK.

**Sub-tasks**
- [ ] Add the `error` attribute to the `receive` macro
- [ ] Handle the error schema in cargo-concordium
- [ ] Handle the error schema in concordium-client
- [ ] Handle the error schema in our NodeJS SDK
- [ ] Describe error schemas in developer documenation
