### ISSUE TITLE
Prepare workshops for GitCoin hackathon

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-rust-smart-contracts#218]
**Task description**

We must prepare the workshops for the [GitCoin hackathon](https://gitcoin.co/hackathon/concordium-identity/onboard).

The workshops are:

1st February @ 12:00 CET - Welcome, Concordium Overview & Intro to Rust (@Bargsteen)
2nd February @ 12:00 CET - Building Smart Contracts (@Bargsteen)
3rd February @ 12:00 CET - Building dApps & Ideation Session (@DOBEN)

**Sub-tasks**
- [ ] Review the [bounty requirements document](https://docs.google.com/document/d/1K_PN8E6whJ9N0Epvqttbmp1MrR822kWHMzEw4U0DVAA/edit) (1 hour)
- [x] Review the twitter spaces document before Wednesday
- [x] Write a short description for each workshop
- [x] Figure out who will do the first workshop
- [ ] Prepare the workshops (2 full working days)
- [ ] Do a dry-run (3 hours total)
