### ISSUE TITLE
Update sponsored transaction dApp once public keys are exposed within the smart contract code

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-rust-smart-contracts#258]
**Task description**

- [x] Update smart contract (e.g. remove `public_key_registry` and related comments):
https://github.com/Concordium/concordium-rust-smart-contracts/tree/main/examples/cis3-nft-sponsored-txs
- [x] Update dApp frontend example to not have a tab anymore to register a `publicKey` via the frontend:
 https://github.com/Concordium/concordium-dapp-examples/tree/main/sponsoredTransactions
- [x] Sponsored transaction tutorial needs to be updated to remove comments about `public_key_registry`:
https://github.com/Concordium/concordium.github.io/pull/786
- [x] Update CIS3 standard to reflect the serialization of the new input parameter to the `permit` function.

**Comment by abizjak** [comment]
@DOBEN Can we close this issue? There is still a PR with testing improvements that has not been merged, but I'm not sure if that is part of this issue or not.

Can you either close this or add details on what is remaining to be done?

**Comment by DOBEN** [comment]
We need to merge the integration tests eventually but we decided to add some better type conversions first to the libraries to simplify the tests.

What is missing:
- Merge of the integration tests.
- Update documentation based on changes merged in the integration tests.

I am closing this issue since the remaining tasks I will keep track of and are rather minor.
