### ISSUE TITLE
Add logos to the published documentation.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-rust-smart-contracts#34]
**Task description**

Add documentation metadata to the published crates, in particular we should set the logo and issue tracker urls, see https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#at-the-crate-level

**Sub-tasks**
- [ ] Add favicon to std, std-derive, contracts-common
- [ ] Add logo to std, std-derive, contracts-common
- [ ] Add issue tracker urls for all of those

The logo and icon are attached
![image](https://user-images.githubusercontent.com/105212/119967709-f32c9f00-bfac-11eb-86d8-09fdf7b65fd0.png)
![image](https://user-images.githubusercontent.com/105212/119967796-06d80580-bfad-11eb-8fa1-2f4bf3d55b3c.png)
