### ISSUE TITLE
Publish smart contract developer videos

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-rust-smart-contracts#366]
**Task description**

**Sub-tasks**
- [x] Send to marketing
- [x] Approve the thumbnails, once created by marketing
- [x] Check the videos once published on YouTube by marketing
   - [x] Also check the subtitles. They should match the scripts.

**Comment by abizjak** [comment]
@Bargsteen I guess this is done now, right?

**Comment by Bargsteen** [comment]
Yep ;)
