### ISSUE TITLE
Remove redundant  `serializationHelper` functions

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-rust-smart-contracts#424]
**Task description**

Smart contract developers do not need to know the `serializationHelperParameter` (CIS3 standard) in their dApps anymore after the merge of:
https://github.com/Concordium/concordium-dapp-examples/pull/83. To reduce the size of the smart contract code (smaller wasm modules save on deployment and executing costs), the not needed `serializationHelper` function should be removed.

**Sub-tasks**
- [ ] Remove function in `cis2-multi`
https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/examples/cis2-multi/src/lib.rs#L1228
- [ ] Remove function in `cis3-nft-sponsored-txs`
https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/examples/cis3-nft-sponsored-txs/src/lib.rs#L710
- [ ] The parameter is used as a `magicNumber` without comment in the browser wallet. Document the parameter and how to re-create it in the browser wallet.
https://github.com/Concordium/concordium-browser-wallet/blob/f30327a57797d69801be7def2893161acbd341b0/packages/browser-wallet/src/popup/pages/SignCIS3Message/SignCIS3Message.tsx#L29
