### ISSUE TITLE
Expose the type of parameters in init and receive signatures

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-rust-smart-contracts#53]
**Task description**

The parameter to smart contracts is accessible via the context as `context.parameter_cursor()`. This is a cursor that implements `Read` and `HasParameter`, so parameters can either be read lazily, or deserialized in one go, for example with `Get::get`.

This is flexible and as efficient as it can be in the general case.

However in the cases where the parameter is used it would be convenient to add better support for just passing it as a parameter.

The proposal is to extend the `init` and `receive` macros with a `parameter` attribute. This attribute already exists and is used to add types to the schema. It currently must always be of the form `parameter = "Foo"`.

I propose that we add additional options to the parameter.
- if `parameter` alone is present among the attributes then the meaning is to expect the `init` or `receive` method to have an additional parameter. In relation to `payable` and `enable_logger` it should fit after `payable` and before `enable_logger`. Amounts are like parameters, so this would make sense. In this form the parameter has no effect on the schema.
- if `parameter(auto)` is present then the meaning is as in the previous item but additionally it adds the parameter type to the schema. It automatically deduces the type from the parameter list of the function.
- if `parameter = "Foo"` is present the meaning is as it is currently.

Subtasks
- [ ] Finalize the design.
- [ ] Implement the changes.
- [ ] Modify existing examples or add new ones. Making sure to observe generated code, size and cost.
- [ ] Update smart contract documentation to reflect the new parameter. This means library documentation as well as developer documentation.
