### ISSUE TITLE
Synchronous contract calls: concordium-std support

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-rust-smart-contracts#71]
**Task description**

Synchronous contract calls change the format of the contract entrypoints fairly significantly. These changes must be reflected in concordium-std to enable painless writing of smart contracts.

The next version of concordium-std will not support V0 contracts anymore, only V1.

Some of the similar changes to contracts are going to be needed for the state implemenation. However the changes should be done in two stages to make them more manageable.

**Sub-tasks**
- [x] Wrap the new host API into ergonomic high-level wrappers (e.g., invoke_contract, transfer, ...)
- [x] Introduce a version 2 of the schema that removes support for the state from the schema, but adds support for return values.
- [x] Revise procedural macros (i.e., the init and receive macros, as well as the schema macro) for the new format of contracts.
- [x] Update testing infrastructure to allow testing of new contracts.
