### ISSUE TITLE
Add helpers to check which mock functions were invoked 

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-rust-smart-contracts#88]
**Task description**

In the test infrastructure, the `TestHost` has a number of helper methods for verifying the transfers that occurred.
It should have the same options for mock functions. 
A bit of experimentation will likely be required to figure out what the helper methods should do and return.

The simplest option is something like:
`TestHost::mocks_invoked(&self) -> Vec<(ContractAddress, EntrypointName)>`

But there could also be method that shows the parameter, amount, etc. used for each invocation of a mock function.

**Sub-tasks**
- [ ] Figure out which helper methods are needed
- [ ] Track the data necessary to said methods (for example by adding a vector of invoked mock functions to `TestHost`)
- [ ] Implement the helper methods

**Comment by Bargsteen** [comment]
The mentioned test infrastructure is now deprecated and replaced by https://docs.rs/concordium-smart-contract-testing/latest/concordium_smart_contract_testing/. Closing this issue, as it is no longer relevant.
